spring:
  application:
    name: book
  cloud:
    config:
      import-check:
        enabled: 'false'
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/dbo?useSSL=false
    username: ronnie
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true